<?php

namespace Frontend\Custom\Block;

use Magento\Framework\View\Element\Html\Link;
use Magento\Framework\View\Element\Template;

class Custom extends Link
{
    protected function _prepareLayout(): Custom
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    protected function _toHtml()
    {
        if ($this->getTemplate()) {
            return parent::_toHtml();
        }
        return '<li><a ' . $this->getLinkAttributes() . ' >' . $this->escapeHtml($this->getLabel()) . '</a></li>';
    }

}
